# Generated by Django 5.2.9 on 2026-01-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenquiry',
            name='occupation',
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='career',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='college',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='field',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='guardian',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='other_source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
