# Generated by Django 5.2.9 on 2026-01-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_faculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Enquiry', 'verbose_name_plural': 'Student Enquiries'},
        ),
        migrations.AddField(
            model_name='studentenquiry',
            name='photo',
            field=models.ImageField(blank=True, help_text="Student's passport size photo", null=True, upload_to='students/photos/'),
        ),
    ]
