# Generated by Django 5.2.9 on 2026-01-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_alter_studentenquiry_options_studentenquiry_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenquiry',
            name='fees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
