# Generated by Django 5.2.9 on 2026-01-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_studentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenquiry',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
