# Generated by Django 5.2.9 on 2026-01-13 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='added_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
