# Generated by Django 5.2.9 on 2026-01-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_alter_student_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
