# Generated by Django 5.2.9 on 2026-01-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_student_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hold_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='is_hold',
            field=models.BooleanField(default=False),
        ),
    ]
