# Generated by Django 5.2.9 on 2026-01-20 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0011_student_hold_duration_student_is_hold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hold_duration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_hold',
        ),
    ]
