# Generated by Django 5.2.9 on 2026-01-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0012_remove_student_hold_duration_remove_student_is_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenquiry',
            name='hold_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentenquiry',
            name='hold_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentenquiry',
            name='is_hold',
            field=models.BooleanField(default=False),
        ),
    ]
