# Generated by Django 5.2.9 on 2026-01-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0013_studentenquiry_hold_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenquiry',
            name='source',
        ),
    ]
