# Generated by Django 5.2.9 on 2026-01-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0014_remove_studentenquiry_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenquiry',
            name='other_source',
        ),
    ]
