# Generated by Django 5.2.9 on 2026-01-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0015_remove_studentenquiry_other_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenquiry',
            name='other_source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studentenquiry',
            name='source',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
