# Generated by Django 5.2.9 on 2026-01-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0016_studentenquiry_other_source_studentenquiry_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenquiry',
            name='hold_duration',
        ),
        migrations.RemoveField(
            model_name='studentenquiry',
            name='hold_start',
        ),
        migrations.RemoveField(
            model_name='studentenquiry',
            name='is_hold',
        ),
        migrations.RemoveField(
            model_name='studentenquiry',
            name='other_source',
        ),
        migrations.RemoveField(
            model_name='studentenquiry',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='studentenquiry',
            name='source',
        ),
    ]
