# Generated by Django 5.2.9 on 2026-01-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0017_remove_studentenquiry_hold_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='hold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='hold_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='paid_fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentpayment',
            name='pending_fees',
            field=models.IntegerField(default=0),
        ),
    ]
