# Generated by Django 5.2.9 on 2026-01-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0018_studentpayment_hold_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpayment',
            name='hold_date',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='hold_duration',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='on_hold',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='paid_fees',
        ),
        migrations.RemoveField(
            model_name='studentpayment',
            name='pending_fees',
        ),
    ]
