# Generated by Django 5.2.9 on 2026-01-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0019_remove_studentpayment_hold_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenquiry',
            name='source',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
