# Generated by Django 5.2.9 on 2026-02-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0020_studentenquiry_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenquiry',
            name='alt_mobile',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
