# Generated by Django 5.2.9 on 2026-02-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0021_studentenquiry_alt_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenquiry',
            name='alt_mobile',
            field=models.CharField(max_length=10),
        ),
    ]
