# Generated by Django 5.2.4 on 2026-02-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0022_alter_studentenquiry_alt_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenquiry',
            name='hold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentenquiry',
            name='hold_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentenquiry',
            name='is_hold',
            field=models.BooleanField(default=False),
        ),
    ]
