# Generated by Django 5.2.9 on 2026-03-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0024_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenquiry',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
