# Generated by Django 5.2.4 on 2026-03-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0025_studentenquiry_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Check', 'Check')], default='Cash', max_length=10),
        ),
    ]
